extends:
  - airbnb
  - plugin:import-order/recommended
env:
  browser: true
  webextensions: true
  jquery: true
plugins:
  - react
  - import-order
globals:
  __ENV__: true
  __VENDOR__: true
  DEBUG: true
  LIVERELOAD: true
  JSONEditor: true
  _: true
rules:
  strict: 0
  arrow-body-style: 0
  no-console: 0
  no-param-reassign: 0
  func-names: 0
  no-else-return: 0
  react/prefer-es6-class: 0
  react/prefer-stateless-function: 0
  quote-props:
    - error
    - consistent
  quotes:
    - error
    - double
